### ISSUE TITLE
Memory recall speed

### ISSUE THREAD

**Issue by haeleng** [bitfocus/companion-module-jvc-ptz#7]
Hi, please implement the preset recall speed

**Comment by JeffreyDavidsz** [comment]
@haeleng I cannot find the propper API call for that, can you show that to me?

**Comment by haeleng** [comment]
Hi Jeffrey,

The code below is what I use in an Arduino Mega
Hope this helps.
It is in the JVC API 1.13 on chapter 3.3.6

Please let me know if you succeed to implement it.
Thanks in advance.

 Request["Command"] = "SetWebSliderEvent";
Request["SessionID"] = SessionID;

JsonObject Request_Params = Request.createNestedObject("Params");
Request_Params["Kind"] = "PresetSpeedBar";
Request_Params["Position"] = Spd;//1-30

SendDefaultJSON_doc("Slider Speed", doc);

regards Henk Levels


Op wo 9 feb. 2022 om 09:09 schreef Jeffrey Davidsz ***@***.***

**Comment by JeffreyDavidsz** [comment]
Hi I've implemented it now, but I don't see it in API v1.18. So my guess is that it might work for you but not for other models. The action is called websliderevent. Let me know if it works

**Comment by haeleng** [comment]
Hi Jeffrey,

How do I update in companion to the latest version you made?

groetjes Henk Levels


Op wo 9 feb. 2022 om 13:17 schreef Henk Levels info ***@***.***>:

**Comment by JeffreyDavidsz** [comment]
Hi make a backup first, download a beta version from the bitfocus.io site. Then just click the installer it will use the same database

**Comment by haeleng** [comment]
Hi Jeffrey,

I found a moment to check your JVC update with my JVC PZ100.
It seems to Work. Thanks a lot
As an addition It should be nice to have a range indication for the
position in the form of a text (1-30) like with the preset number (see
screenshot below)
[image: image.png]

I agree that the value PresetSpeedbar is not found in the API.
However in the Web App there is also a slider for setting the recall speed
(see screenshot below)
I could not find the value in the API for this recall speed slider
So I captured the PresetSpeedbar value via Fiddler. (which is a web
debugger)

When is this new Web Slider Event function available in the official
Companion release?

[image: image.png]

regards Henk Levels


Op wo 9 feb. 2022 om 15:20 schreef Jeffrey Davidsz ***@***.***

**Comment by JeffreyDavidsz** [comment]
@haeleng can you post the screeenshots on the github site? I think they get lost with email

**Comment by haeleng** [comment]
I found a moment to check your JVC update with my JVC PZ100.
It seems to Work. Thanks a lot
As an addition It should be nice to have a range indication for the position in the form of a text (1-30) like with the preset number (see screenshot below)
![image](https://user-images.githubusercontent.com/64407637/153585987-0e56f2e6-3bb5-4ab5-8868-835cc16864bf.png)


I agree that the value PresetSpeedbar is not found in the API.
However in the Web App there is also a slider for setting the recall speed (see screenshot below)
I could not find the value in the API for this recall speed slider
So I captured the PresetSpeedbar value via Fiddler. (which is a web debugger)

When is this new Web Slider Event function available in the official Companion release?

![image](https://user-images.githubusercontent.com/64407637/153586066-347ed2b2-9461-4644-aab0-c74804286257.png)

**Comment by haeleng** [comment]
Hi Jeffrey,

See Github for a copy of my email with screenshots

regards Henk Levels


Op vr 11 feb. 2022 om 10:10 schreef Jeffrey Davidsz <
***@***.***>:

**Comment by JeffreyDavidsz** [comment]
@haeleng I see what you mean, the way I set it up now, is to be flexible in the WebSliderEvent (selecting a dropdown for options). Unfortunately this limits the second option as it needs to me general to all functions selected by the dropdown.
Its ok to have the function in there even when not all models support it.
It's hard to say in which release it will be, as the module had changed a lot (rewrite for the new API) and more testing need to be done, I think I wont be on the next one. But just keep using the Beta!
