### ISSUE TITLE
JVC GY-HC900 Connected Camera Control

### ISSUE THREAD

**Issue by Moving-Light** [bitfocus/companion-module-jvc-ptz#8]
I am looking to see if the [JVC PTZ](https://github.com/bitfocus/companion-module-jvc-ptz) module could be updated to use the v114 API and to add compatibility for the [GY-HC900](http://pro.jvc.com/prof/attributes/features.jsp?model_id=MDL102520&feature_id=01) Connected Camera series.  Being able to control zoom, iris, start/stop the stream and return over IP, and tally would be great to have.  I have the link to the updated v114 docs below:

[http://pro.jvc.com/pro/attributes/ip/manual/JvcCamcorderApiReferenceV114_public.pdf](http://pro.jvc.com/pro/attributes/ip/manual/JvcCamcorderApiReferenceV114_public.pdf)

**Comment by JeffreyDavidsz** [comment]
@Moving-Light I've just updated the module to use v1.18. But I need to check backward compatibility. It might work for your camera to. Will be in the builds in 15min

**Comment by dnmeid** [comment]
This issue is stale for two years. Closing it now.
